## This should be places in the plugin directory
## for more help configuring see the wiki
## https://github.com/alkarinv/BattleArena/wiki
## Change this file to customize your event

quake:
    enabled: true
    type: arena
    command: quake
    database: quake
    rated: true
    prefix: "&6[Quake]&e"
    nTeams: 2
    teamSize: 1-10
    matchTime: 300
    secondsToLoot: 0
    onJoin:
        options: [pvpOff, deEnchant, wgClearRegion]
    preReqs:
        options: [clearInventory]
    onPreStart:
        options: [pvpOff, deEnchant, clearInventory]
    onStart:
        options: [teleportIn, pvpOn, blockBreakOff, wgNoLeave]
    onSpawn:
        options: [deEnchant, giveItems, hunger=20, health=20]
        giveClass:
            default: quakeman
        items: # ignored if options doesnt have "giveItems"
            - bread: 5
    onDeath:
        options: [respawn, clearInventory]
    onComplete:
        options: [teleportOut, deEnchant, clearInventory, wgClearRegion]
    winner:
        options: [health=20, hunger=20, money=500]
